"""Interfaz (Protocolo) del repositorio de categorías — principio DIP."""
import uuid
from typing import Protocol

from app.infrastructure.database.models.category_model import CategoryModel


class ICategoryRepository(Protocol):
    async def get_by_id(self, category_id: uuid.UUID) -> CategoryModel | None: ...
    async def get_by_slug(self, slug: str) -> CategoryModel | None: ...
    async def get_by_name(self, name: str) -> CategoryModel | None: ...
    async def list_active(self) -> list[CategoryModel]: ...
    async def create(self, **kwargs: object) -> CategoryModel: ...
    async def deactivate(self, category_id: uuid.UUID) -> CategoryModel | None: ...
