"""Interfaz (Protocolo) del repositorio de ubicaciones — principio DIP."""
import uuid
from typing import Protocol

from app.infrastructure.database.models.location_model import LocationModel


class ILocationRepository(Protocol):
    async def get_by_id(self, location_id: uuid.UUID) -> LocationModel | None: ...
    async def get_by_code(self, code: str) -> LocationModel | None: ...
    async def list_active(self) -> list[LocationModel]: ...
    async def create(self, **kwargs: object) -> LocationModel: ...
    async def deactivate(self, location_id: uuid.UUID) -> LocationModel | None: ...
