"""Interfaz del repositorio de insumos — principio DIP."""
import uuid
from decimal import Decimal
from typing import Protocol

from app.infrastructure.database.models.supply_model import SupplyItemModel


class ISupplyRepository(Protocol):
    async def get_by_id(self, item_id: uuid.UUID) -> SupplyItemModel | None: ...
    async def get_by_sku(self, sku: str) -> SupplyItemModel | None: ...
    async def list_active(
        self,
        category_id: uuid.UUID | None = None,
        location_id: uuid.UUID | None = None,
    ) -> list[SupplyItemModel]: ...
    async def list_below_minimum(self) -> list[SupplyItemModel]: ...
    async def create(self, **kwargs: object) -> SupplyItemModel: ...
    async def update_stock(
        self, item_id: uuid.UUID, new_stock: Decimal
    ) -> SupplyItemModel: ...
    async def deactivate(self, item_id: uuid.UUID) -> SupplyItemModel | None: ...
