"""Interfaz del repositorio de usuarios — principio DIP."""
import uuid
from typing import Protocol

from app.infrastructure.database.models.user_model import UserModel


class IUserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> UserModel | None: ...
    async def get_by_email(self, email: str) -> UserModel | None: ...
    async def list_active(self) -> list[UserModel]: ...
    async def list_all(self) -> list[UserModel]: ...
    async def create(self, **kwargs: object) -> UserModel: ...
    async def deactivate(self, user_id: uuid.UUID) -> UserModel | None: ...
